#!/usr/bin/env python

import schemdraw
import schemdraw.elements as e
import schemdraw.elements
from time import time

e.style(e.STYLE_IEC)
schemdraw.config(font="NewComputerModernMath", mathfont="cm")

start_time = time()


with schemdraw.Drawing(file=f"kom-krets.svg", show=False) as d:
    global u
    u = d.unit
    e.BatteryCell().left(2*u)
    e.Line().up() 
    e.Resistor().right(1.25*u).label("$R_3$")
    d.push()
    e.Line().up(u/4)
    e.Resistor().right(u/2).label("$R_1$")
    e.Line().down(u/4)
    d.pop()
    e.Line().down(u/4)
    e.Resistor().right(u/2).label("$R_2$")
    e.Line().up(u/4)
    e.Line().right(u/4)
    e.Line().down()



with schemdraw.Drawing(file=f"ex-upg.svg", show=False) as d:
    e.BatteryCell().left(2*u).label("20 V")
    e.Line().up() 
    e.Resistor().right(1.25*u).label("$R_3 = 20 Ω$")
    d.push()
    e.Line().up(u/4)
    e.Resistor().right(u/2).label("$R_1 = 100 Ω$")
    e.Line().down(u/4)
    d.pop()
    e.Line().down(u/4)
    e.Resistor().right(u/2).label("$R_2 = 150 Ω$", loc="B")
    e.Line().up(u/4)
    e.Line().right(u/4)
    e.Line().down()

with schemdraw.Drawing(file=f"ex-upg2.svg", show=False) as d:
    e.BatteryCell().left(2*u).label("20 V")
    e.Line().up() 
    e.Resistor().right(1.25*u).label("$R_3 = 20 Ω$")
    e.Resistor().right(u/2).label("$R_{12} = 60 Ω$")
    e.Line().right(u/4)
    e.Line().down()

with schemdraw.Drawing(file=f"bild1.svg", show=False) as d:
    e.BatteryCell().right(4*u)
    e.Line().down(u)
    e.Line().left(.4*u)
    d.push()
    e.Line().up(.5*u)
    e.Resistor().left(2*u).label("$R_4$")
    e.Line().down(.5*u)
    d.pop()
    d.push()
    e.Resistor().left(2/3*u).label("$R_7$")
    e.Resistor().left(2/3*u).label("$R_6$")
    e.Resistor().left(2/3*u).label("$R_5$")

    d.pop()
    e.Line().down(.5*u)
    e.Resistor().left(2*u).label("$R_8$")
    e.Line().up(.5*u)
    e.Line().left(.2*u)
    d.push()
    e.Line().up(.3*u)
    e.Resistor().left(u).label("$R_1$")
    e.Line().down(.3*u)
    d.pop()
    e.Line().down(.3*u)
    e.Resistor().left(u/2).label("$R_2$")
    e.Resistor().left(u/2).label("$R_3$")
    e.Line().up(.3*u)
    e.Line().left(0.4*u)
    e.Line().up()

with schemdraw.Drawing(file=f"bild2.svg", show=False) as d:
    e.BatteryCell().right(4*u)
    e.Line().down(u)
    e.Line().left(.4*u)
    d.push()
    e.Line().up(.5*u)
    e.Resistor().left(2*u).label("$R_4$")
    e.Line().down(.5*u)
    d.pop()
    d.push()
    e.Resistor().left(2/3*u).label("$R_7$")
    e.Resistor().left(2/3*u).label("$R_6$")
    e.Resistor().left(2/3*u).label("$R_5$")
    d.pop()
    e.Line().down(.5*u)
    e.Resistor().left(2*u).label("$R_8$")
    e.Line().up(.5*u)
    e.Line().left(.2*u)
    d.push()
    e.Line().up(.3*u)
    e.Resistor().left(u).label("$R_1$")
    e.Line().down(.3*u)
    d.pop()
    e.Line().down(.3*u)
    e.Resistor().left(u).label("$R_{23}$")
    e.Line().up(.3*u)
    e.Line().left(0.4*u)
    e.Line().up()

with schemdraw.Drawing(file=f"bild3.svg", show=False) as d:
    e.BatteryCell().right(4*u)
    e.Line().down(u)
    e.Line().left(.4*u)
    d.push()
    e.Line().up(.5*u)
    e.Resistor().left(2*u).label("$R_4$")
    e.Line().down(.5*u)
    d.pop()
    d.push()
    e.Resistor().left(2/3*u).label("$R_7$")
    e.Resistor().left(2/3*u).label("$R_6$")
    e.Resistor().left(2/3*u).label("$R_5$")
    d.pop()
    e.Line().down(.5*u)
    e.Resistor().left(2*u).label("$R_8$")
    e.Line().up(.5*u)
    e.Line().left(.2*u)
    e.Resistor().left(u).label("$R_{123}$")
    e.Line().left(0.4*u)
    e.Line().up()
    
with schemdraw.Drawing(file=f"bild4.svg", show=False) as d:
    e.BatteryCell().right(4*u)
    e.Line().down(u)
    e.Line().left(.4*u)
    d.push()
    e.Line().up(.5*u)
    e.Resistor().left(2*u).label("$R_4$")
    e.Line().down(.5*u)
    d.pop()
    d.push()
    e.Resistor().left(2*u).label("$R_{567}$")
    d.pop()
    e.Line().down(.5*u)
    e.Resistor().left(2*u).label("$R_8$")
    e.Line().up(.5*u)
    e.Line().left(.2*u)
    e.Resistor().left(u).label("$R_{123}$")
    e.Line().left(0.4*u)
    e.Line().up()

with schemdraw.Drawing(file=f"bild5.svg", show=False) as d:
    e.BatteryCell().right(4*u)
    e.Line().down(u)
    e.Line().left(.4*u)
    e.Resistor().left(2*u).label("$R_{45678}$")
    e.Line().left(.2*u)
    e.Resistor().left(u).label("$R_{123}$")
    e.Line().left(0.4*u)
    e.Line().up()

with schemdraw.Drawing(file=f"bild6.svg", show=False) as d:
    e.BatteryCell().right(4*u)
    e.Line().down()
    e.Resistor().left(4*u).label("$R_{tot}$")
    e.Line().up()

print(f"Done in {time()-start_time} s")
