name: Deploy website
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'book.toml'
      - 'src/**'
      - 'theme/**'
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # to checkout private repo
      id-token: write # to use actions/deploy-pages
      pages: write # to push to a github pages site
    steps:

      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Build mdBook
        run: mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
